### ISSUE TITLE
tidak bisa di install di woocommerce

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#1]
pak ada bugs untuk penginstallan terdapat notif Parse error: syntax error, unexpected '[' in /home/xxxxxx/public_html/wp-content/plugins/woocommerce-indo-shipping-master/lib/wcis-data.php on line 13

**Comment by hrsetyono** [comment]
Boleh tahu PHP nya versi berapa? Plugin nya tidak support di bawah 5.6

**Comment by frezendisney** [comment]
iya pak PHP versi saya 5.4 pak. saat ini saya sedang proses  upgrade ke versi php 5.6.25.

**Comment by frezendisney** [comment]
pak setelah saya upgrade ke versi 5.6.24, plugin sdh bisa diaktifkan. akan tetapi setelah mengikuti step2 yg bpk berikan. ada kendala setelah saya setup dan memasukan API rajaongkir pro. saya cb checkout tidak muncul pak. saya punya plugin yg biasa untuk yg started itu muncul kotanya. untuk yg ini tidak muncul. bisa bpk review ke website saya http://todaybestoffer.xyz/ karena tidak ke load pak datanya

**Comment by frezendisney** [comment]
untuk woocomerce saya Version 2.6.4 pak

**Comment by hrsetyono** [comment]
Kemungkinan clash dengan plugin atau theme lain. Bisa di tes dengan deactivate plugin shipping lain dan install theme WooCommere yang asli nama nya Storefront.

Kalau di Storefront bisa jalan, berarti masalah di Theme.

**Comment by frezendisney** [comment]
untuk versi woocomerce saya apakah bermasalah pak ? untuk expedisi yg saya pakai hanya punya bpk saja yg terinstall. baik pak saya cb dlu

**Comment by frezendisney** [comment]
saya sdh install themes Storefront tetep saja pak tidak muncul pak.

**Comment by frezendisney** [comment]
apa ini bermasalah di versi woocomerceny ya pak ?

**Comment by hrsetyono** [comment]
WooCommerce yg saya pakai juga 2.6.4. Apa bapak sudah setting Shipping Zone sampai memilih servis seperti REG, OKE, YES?

**Comment by frezendisney** [comment]
sudah pak. apa bpk bisa bantu remote punya website saya pak. saya kirim akses login ke  website saya pak. via email. gimana ? mohon bantuanya pak.

**Comment by hrsetyono** [comment]
Coba di email

**Comment by frezendisney** [comment]
saya sudh kirim pak ke email.

**Comment by frezendisney** [comment]
gimana pak ? kira2 bermasalah dimana pak ?

**Comment by hrsetyono** [comment]
Plugin sudah saya fix di versi terbaru 0.3.1.

Terima kasih
