### ISSUE TITLE
posisi disctrik dan bugs di field shipping

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#10]
pak mau tanya kenapa posisi distrik tidak bisa fix posisi ya pak. saat di rubah dia gk ikut kerubah seperti ini http://prntscr.com/f2hdjj padahal field perubahan tersebut sudh saya disable. tapi tetap tidak bisa dirubah. oh iya saya mencoba tanpa plugin apapun untuk custom field dan saya cb install plugin bapak akan tetapin defaultnya di field shipping berantakan. bpk bisa cek sndiri.

**Comment by frezendisney** [comment]
maaf pak untuk yg problem field shipping di skip aja karena gk ada masalah saat saya cba. ternyata bentrok dengan plugin.. problem hanya itu sih pak cara fix untuk colom disctrik jd saya dirubah posisi dia tidak kerubah posisinya.

**Comment by frezendisney** [comment]
ini problem di shipping fieldnya pak http://prntscr.com/f2hmjp . ini tanpa plugin fix. ada masalah di field shipping.

**Comment by frezendisney** [comment]
saya sudh coba pak. tapi gak ada yg work. klw pakai plugin gk ada yg bisa fielnya jdi berantakan. untuk solusinya gmn y pak? agar bisa fix untuk disctiknya karena apabila dirubah dia ikut berubah posisiinya

**Comment by frezendisney** [comment]
http://prntscr.com/f2hx9i.

untuk field shipping gk ada maslah sih pak udh gk berantakan yg tdi. ,. saya hnya  rubah begini 

function reorder_fields($fields) {
    // default priorities:
    // 'first_name' - 10
    // 'last_name' - 20
    // 'company' - 30
    // 'country' - 40
    // 'address_1' - 50
    // 'address_2' - 60
    // 'city' - 70
    // 'state' - 80
    // 'postcode' - 90
    $fields['state']['priority'] = 42;
    $fields['city']['priority'] = 61;
    $fields['postcode']['priority'] = 91;

    return $fields;
  }

**Comment by frezendisney** [comment]
menurut saya lebih baik yg versi beta_3 pak. soalnya klw yg beta4 klw diurutin berdasaran fiel jdi eroor.

**Comment by hrsetyono** [comment]
Hmm untuk sementara akan saya hilangkan kode mengubah urutan field. Memang sebaiknya kode itu ditaruh di theme ato plugin terpisah.

**Comment by frezendisney** [comment]
oh iya pak. mending di taruh di themes pak di fuunction.php agar mudah melihatnya. dan mempermudah perubahan data fieldnya.

**Comment by hrsetyono** [comment]
Oke sudah saya update di 1.0.0-beta5. Terima kasih sudah bantu laporan nya

**Comment by rumahbudi** [comment]
Mas, kenapa calculatingnya di checout enggak bekerja yah? apakah harus dimasukan beratnya juga?

**Comment by hrsetyono** [comment]
@rumahbudi Kode pos nya sudah diisi?

**Comment by rumahbudi** [comment]
Sudah di isi sih, tapi pas place order dihalaman doku keluar biaya kirim
![screenshot-www kawantrip com-2017-05-01-23-04-11](https://cloud.githubusercontent.com/assets/15171293/25584982/8db5c770-2ec2-11e7-93a7-63ffa0510aae.png)
![screenshot-staging doku com-2017-05-01-23-05-32](https://cloud.githubusercontent.com/assets/15171293/25585012/b15e5458-2ec2-11e7-8b34-090bd759e3b2.png)

**Comment by hrsetyono** [comment]
@rumahbudi Coba matikan semua plugin kecuali ini dan WooCommerce, lalu ganti theme dengan Storefront (free).

Kalau dengan itu tidak ada masalah berarti ada clash dengan plugin atau theme nya. Step berikutnya diperiksa satu2 plugin mana yang clash.

**Comment by rumahbudi** [comment]
Hallo mas, yang masalah templatenya ternyata

Tapi posisi disittriknya kebalik enggak yah? Soalnya dipilih propinsi baru
keluar,

website kawantrip.com

**Comment by hrsetyono** [comment]
@rumahbudi Dari awal posisi field nya sudah begitu. Bisa diubah pakai kode dari frezendisney diatas.
