### ISSUE TITLE
Missing Function

### ISSUE THREAD

**Issue by asisten** [hrsetyono/woocommerce-indo-shipping#11]
versi Woocommerce: 3.0.4
pada rilis terbaru 1.0.0 beta 4:
`Fatal error: Call to undefined method WCIS_API::get_cities()  // sepertinya fungsi ini dihilangkan di rilis terbaru, pada rilis sebelumnya ada`

Ketika saya tambahkan function get_cities pada rilis lama tsb ke rilis baru, error hilang, namun shipping methodnya tidak terdeteksi pada frontend

kemudian beberapa error lainnya
`Warning: array_key_exists() expects parameter 2 to be array, null given in /.../wp-content/plugins/woocommerce-indo-shipping-1.0.0-beta4/admin/wcis-data.php on line 16`

ada lagi tapi lupa saya catat

**Comment by asisten** [comment]
Oh iya baru teringat lagi, problem pada metode file_get_contents utk mengambil data json ya?
Jika webnya https maka akan error.

Saya belum cek konfigurasi hosting apakah terinstall php_openssl

Tapi, bagaimana dengan opsi mengganti file_get_contents dengan curl dan verifynya di set false? Ini kan untuk ambil data wilayah saja ya?

**Comment by hrsetyono** [comment]
@asisten 

1. Error tersebut di halaman apa ya? Function nya memang saya hilangkan tapi di plugin tidak ada yg memanggil function itu lagi.

1. Hmm poin yg bagus, selama ini belum saya coba di https, coba saya cari cara pakai curl.

**Comment by asisten** [comment]
Error ada Pada halaman setup plugins ini, ketika mulai menentukan base kota.

Pada tanggal 30 Apr 2017 7.56 PM, "Henner R Setyono" <
notifications@github.com> menulis:

**Comment by hrsetyono** [comment]
Oke sudah saya fix di 1.0.0-beta5. Tolong di tes lagi ya. Terima kasih.
