### ISSUE TITLE
Invalid API Key. Is there empty space before / after it?

### ISSUE THREAD

**Issue by GembeJr** [hrsetyono/woocommerce-indo-shipping#13]
akun sudah pro dan tidak ada "empty space", tapi masih Invalid API KEY, kenapa yah gan?

**Comment by hrsetyono** [comment]
coba test di Postman untuk call API nya. Install dari Chrome app store.

Pakai GET `http://pro.rajaongkir.com/api/province` dan Headers > `key` diisi API key mu.

**Comment by GembeJr** [comment]
bisa ko gan ,
`{
  "rajaongkir": {
    "query": {
      "xxx": ""
    },
    "status": {
      "code": 200,
      "description": "OK"
    },
    "results": [
      {
        "province_id": "1",
        "province": "Bali"
      },
      {
        "province_id": "2",
        "province": "Bangka Belitung"
      },`

**Comment by GembeJr** [comment]
<img width="1280" alt="screen shot 2017-05-02 at 5 07 12 pm" src="https://cloud.githubusercontent.com/assets/7575645/25614207/3abed658-2f5b-11e7-8777-49131f4f6bea.png">
hasil screennya..

**Comment by hrsetyono** [comment]
Coba disable semua plugin kec WooCommerce sama shipping ini. Dan install theme Storefront.

**Comment by GembeJr** [comment]
sudah saya lakukan dan masih tidak berhasil

plugin aktif
<img width="1280" alt="screen shot 2017-05-03 at 1 29 56 am" src="https://cloud.githubusercontent.com/assets/7575645/25633127/50fb2e9a-2fa0-11e7-89c3-b76e89bb19f8.png">

panel key yang bermasalah ..
<img width="1280" alt="screen shot 2017-05-03 at 1 32 28 am" src="https://cloud.githubusercontent.com/assets/7575645/25633239/ab85fc28-2fa0-11e7-8327-f94931612c32.png">


panel petunjuk yg ada di git sudah sesuai ...
<img width="1280" alt="screen shot 2017-05-03 at 1 35 02 am" src="https://cloud.githubusercontent.com/assets/7575645/25633322/ec025eae-2fa0-11e7-91c7-56cf890040ba.png">

**Comment by GembeJr** [comment]
oh iya ketinggalan, ini tema yang saya gunakan

<img width="1280" alt="screen shot 2017-05-03 at 1 38 12 am" src="https://cloud.githubusercontent.com/assets/7575645/25633491/709b7c2c-2fa1-11e7-95e9-10de6cdbfb2f.png">

apakah ada solusi?

**Comment by hrsetyono** [comment]
Kemungkinan PHP bapak tidak ada CURL nya. Coba cek di active modules nya pakai `phpinfo()`

**Comment by GembeJr** [comment]
<img width="1280" alt="screen shot 2017-05-03 at 8 05 01 am" src="https://cloud.githubusercontent.com/assets/7575645/25645372/9342e036-2fd7-11e7-8f98-cb76c0f7bd82.png">

php CURL tersedia

**Comment by hrsetyono** [comment]
Sepertinya karena https. Karena saya tdk punya akses ke web yg https, bisa tolong dibantu solusi nya? Mungkin ada di [thread ini](http://stackoverflow.com/questions/4372710/php-curl-https).

Trims

**Comment by frezendisney** [comment]
@GembeJr  @hrsetyono sepertinya bukan masalah https deh pak. saya sendiri pakai https. sepertinya ini dari masalah server.

**Comment by amrikarisma** [comment]
masih belum ada solusi ya? saya mengalami masalah yang sama

**Comment by hrsetyono** [comment]
@amrikarisma Iya pak, harus API pro, sudah saya cantumkan di README nya. Trims

**Comment by rahmanshu** [comment]
saya pake yg pro tidak bisa mas
