### ISSUE TITLE
menambahkan estimasi shipping

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#14]
pak mau tanya lokasi file untuk menambahkan estimasi shipping dimana ya pak? agar saya mudah untuk custom estimasi shipping

**Comment by hrsetyono** [comment]
Apa itu estimasi shipping?

**Comment by frezendisney** [comment]
seperti ini contohnya JNE REG 2-3 Hari : Rp. 9000 

saat ouput shipping muncul

**Comment by hrsetyono** [comment]
itu ada di `init-zones` sepertinya

**Comment by frezendisney** [comment]
oh bgtu pak Ada di ini-zone. saat checkout saya check di ie muncul notif error pak http://prntscr.com/f48k0w

**Comment by hrsetyono** [comment]
trims laporan nya, coba saya cek di IE.

Dan kalau boleh, plugin editannya tolong ditaruh di github dong, biar bisa saya lihat improvement apa yg perlu. Trims

**Comment by frezendisney** [comment]
untuk penambahn estimasi shipping sdh bisa pak. terima kasih. takut beda pak karena karena saya rubah untuk nama servicenya. jdi sya hanya menampilkan estima shipping aja dan harga. bisa di cek pak carimug.com . dan yg mengerjakan bukan saya pak team saya. jdi gk paham caranya taruh di github maaf y pak.
