### ISSUE TITLE
no methods shipping available

### ISSUE THREAD

**Issue by vodkaiserz** [hrsetyono/woocommerce-indo-shipping#15]
pak Henner,

saya sudah install sesuai petunjuk..
untuk sampai pemillihan provinsi, kota dan kecamatan sudah bisa , namun di shipping costnya kenapa tulisannya: _

> "There are no shipping methods available. Please double check your address, or contact us if you need any help."

_
terima kasih.

**Comment by hrsetyono** [comment]
Apa semua field sudah diisi? termasuk kode pos dll.

**Comment by vodkaiserz** [comment]
sudah pak, produknya juga sudah ada berat(weight)nya..
![untitled](https://cloud.githubusercontent.com/assets/18417092/25771279/bdd4bb56-3277-11e7-82da-4d5b00c0c953.jpg)

**Comment by mangcoding** [comment]
sama nih mas saya pun mengalami hal yang sama

**Comment by hrsetyono** [comment]
@vodkaiserz @mangcoding Website bapak https? Sepertinya ada bug di https tapi saya tidak bisa ngetes karena ga punya web yg https.

Coba (1) theme diganti menggunakan Storefront dan (2) di echo `phpinfo()`, apa ada CURL nya? trims

**Comment by frezendisney** [comment]
@vodkaiserz @mangcoding  apa sudh pakai versi terahir beta'y ?

**Comment by mangcoding** [comment]
jadi begini pak, pas di list sudah muncul yang di sebelah kanan itu, namun pas saya submit muncul error 
"No shipping method has been selected. Please double check your address, or contact us if you need any help."

**Comment by asisten** [comment]
Saya menemukan problem ini kalau jenis produknya adalah variable

**Comment by asisten** [comment]
Melihat dari hasil debug console:
`TypeError: cityRaw is undefined`

Sepertinya problemnya disini ya?
wcis-data.php:108
```
private static function _get_json_file($filename) {
    $fileurl = WCIS_DIR . "/data/$filename";
    $args = array(
      'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
      ),
    );

    $fileraw = file_get_contents($fileurl, false, stream_context_create($args) );
    return json_decode($fileraw, true);
  }
```

**Comment by hrsetyono** [comment]
@asisten Bapak sudah coba kalau theme Storefront? Saya coba di Storefront dan theme buatan saya, tidak ada error itu. Jalan di localhost dan live site (non SSL).

Apakah website bapak ada SSL? Saya belum tes di yang ada SSL nya

**Comment by asisten** [comment]
Saya pake ssl, blm coba pakai thenes storefrony,memang bs jd krn thenesnya.

CityRaw itu ambil data post dr get json pd file wcis data kan ya pak?

Pada tanggal 4 Jun 2017 08.54, "Henner R Setyono" <notifications@github.com>
menulis:

**Comment by frezendisney** [comment]
@asisten iya pak saya jg gtu tapi itu berlaku hanya untuk admin. ketika user baru enggak masalah sih. mestinya gk ada masalah pak untuk ssl. diwebsite saya normal2 aja. mungkin pak @hrsetyono punya solusi lain.

**Comment by frezendisney** [comment]
@asisten iya pak saya jg gtu tapi itu berlaku hanya untuk admin. ketika user baru enggak masalah sih. mestinya gk ada masalah pak untuk ssl. diwebsite saya normal2 aja. mungkin pak @hrsetyono punya solusi lain.

**Comment by hrsetyono** [comment]
@asisten iya, cuma ngambil json file statik. Tadinya API call ke rajaongkir tapi pikir2 terlalu lama kalau dikit2 panggil API nya. jadi aku dump ke file.

Ini saya coba2, baru sadar kalau calculator shipping pas di cart nya rusak, kalau di checkout ga masalah. Ga tau cara benerin nya. Aku liat2 plugin ongkir lain pada skip Cart calculator nya.

**Comment by asisten** [comment]
@frezendisney : Iya benar nih, errornya ketika login sebagai admin saja, ketika saya logout, order dan langsung checkout sukses.  Tapi tetap ketika masuk halaman cart (tidak langsung checkout) ketemu error:
`TypeError: cityRaw is undefined` ketika di lihat di console.

@hrsetyono :  Benar pak, errornya ketika calculate shipping atau ketika masuk halaman cart, klo diskip langsung checkout gak masalah. Mungkin kaitan masalahnya dengan replacement field2 address? Saya belum explore lg script plugins Bapak apa ada filter atau action yang replace field2 address default bawaan woocommerce

**Comment by hrsetyono** [comment]
@asisten Untuk sementara bapak bisa disable cart calculator dari setting WooCommerce nya.

Sebenarnya dari awal cart calculator memang tidak saya kerjakan karena nambah2-in step. Lebih baik langsung lompat ke checkout.

**Comment by asisten** [comment]
@hrsetyono  iya pak saya saat ini memang mendisablenya karena tidak membutuhkan calculator shipping tsb

**Comment by hrsetyono** [comment]
Isu ini disebabkan karena API request yg tidak stabil. Di update 1.1.1 seharusnya sudah jauh lebih baik, selama ini tidak ada masalah di toko-toko saya.

Untuk cart calculator, saya tidak menyarankan di enable karena membingungkan konsumen.

Terima kasih
