### ISSUE TITLE
Menampilkan Nama Kurir

### ISSUE THREAD

**Issue by asisten** [hrsetyono/woocommerce-indo-shipping#16]
Halo pak @hrsetyono 

Apakah pada plugins ini nama kurir disimpan dalam post_meta pada post shop_order ?
Saya ingin coba integrasikan dengan tracking code, jadi customer cukup mengetikan no order mereka maka otomatis akan tampil status pengiriman mereka. Sementara ini Saya implementasi di themes seperti ini:

```
function cek_tracking($post_id)
{
$kurir = get_post_meta( $post_id, 'kurir_pengiriman', true );	// ini yang ingin Saya ambil otomatis berdasar post id dan post meta shop_order untuk kurir pada plugin ini, kurir_pengiriman sementara ini diinput manual pada halaman orders

$kode = get_post_meta( $post_id, 'kode_tracking', true );  

if (!$kurir)
{
return "No Order yang Anda masukan salah...";	
}
	
if (!$kode)
{
return "Pesanan Anda saat ini masih dalam tahap pickup oleh kurir, silahkan dicek kembali nanti.";	
}

// dokumentasi waybill di rajaongkir
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "http://pro.rajaongkir.com/api/waybill",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "waybill=$kode&courier=$kurir",
  CURLOPT_HTTPHEADER => array(
    "content-type: application/x-www-form-urlencoded",
    "key: asdf"
  ),
));

$respon = curl_exec($curl);

$hasil = json_decode($respon, true);

return $hasil;

}	
```

Jika saat ini belum diimplementasi nama kurir ke post meta, bagaimana cara mengambil kode kurir ketika proses checkout? mungkin saya akan implementasi add post meta  kurir setelah action after new order.

Terima kasih sebelumnya

**Comment by hrsetyono** [comment]
Kode kurir disimpan di JSON file statik, ada kode servis nya juga. Saya kurang tau apakah disimpan di shop order atau tidak. Tidak ada yang saya ganti, jadi kalau defaultnya disimpan, berarti ada.

**Comment by asisten** [comment]
Ok sudah ketemu, kurir pengiriman disimpan pada meta key:  _shipping_method  

Dapat dicek dengan menggunakan fungsi get_post_meta:
`var_dump( get_post_meta(id post shop_order));`
