### ISSUE TITLE
BIsakah Menggunakan API Starter

### ISSUE THREAD

**Issue by haifahrul** [hrsetyono/woocommerce-indo-shipping#17]
@hrsetyono Apakah memungkinan plugin ini berjalan jika saya mengganti url ke `	http://api.rajaongkir.com/starter` ?

**Comment by haifahrul** [comment]
Setelah saya testing memang harus menggunakan api pro. 

Mohon izin untuk saya custom agar bisa digunakan api starter.

Terima kasih :-)

**Comment by hrsetyono** [comment]
Starter tidak kita support karena Starter hanya support ongkir ke kabupaten, sedangkan harga antar kecamatan bisa berbeda, terutama di luar pulau jawa.

SIlahkan di fork kode nya, kalau sudah selesai bisa tolong di share? hehe

**Comment by wolfcoder** [comment]
Gimana ada perkembangan untuk yang bisa di pake akun starter gag. hehehehe...

**Comment by hrsetyono** [comment]
Saya tidak sarankan untuk pakai starter karena ongkir bisa berbeda antar kecamatan. Kalau lebih murah ya ga masalah, kita bisa lampirkan uang cash di paket. Kalau kurang? Masa repot2 chat dengan pelanggan untuk transfer 2000 lagi
