### ISSUE TITLE
Mau Tanya Splitting Shipping Packages vendor tidak muncul saat dicheckout

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#19]
pak mau tanya kenapa ya saya coba install ini https://wordpress.org/plugins/packages-configuration-for-woocommerce/ dan https://wordpress.org/plugins/dokan-lite/ saat order bagian shipping yg displit tindak mau ngeload ya pak seperti gambar ini http://prntscr.com/g3ucbv . kira2 knp ya pak? seharusnya kan ngikut ngeload jg data shipping seperti diatas.

**Comment by hrsetyono** [comment]
Saya malah baru tau kalau Woocommerce ada fitur seperti itu. Mungkin ada API baru untuk shipping method nya. Untuk saat ini saya masih belum sempat untuk mengecek, kalau bapak ketemu dokumentasi nya, boleh bantu di share?

Trims

**Comment by frezendisney** [comment]
Iya pak. Itu plugin udh dr thun 2015 pak. Itu berjlan pak kalau shiipingnya
flat. Ataupun free. Tpi klw raja ongkir dia gk mau ngambil. Dokumentasi di
github dia pak. Blum bnyk org pakai. Padahl ini keren bngt pak. Ya
mudah2han bsa nih pak di integrasikan dengam plugin bpk.
