### ISSUE TITLE
City tidak keluar

### ISSUE THREAD

**Issue by amrikarisma** [hrsetyono/woocommerce-indo-shipping#20]
![image](https://user-images.githubusercontent.com/4257664/29071481-0131a84c-7c6e-11e7-9a1e-ab63f7f2dc15.png)

City tidak keluar setelah pilih province

**Comment by amrikarisma** [comment]
solved selector by class tidak ditemukan kalo single country

**Comment by hrsetyono** [comment]
Trims laporannya, sepertinya memang benar kalau city tidak berfungsi kalau Country field nya bukan dropdown. Coba saya cari cara
