### ISSUE TITLE
Dropdown List Pilihan Ongkir

### ISSUE THREAD

**Issue by visitekasia** [hrsetyono/woocommerce-indo-shipping#22]
**Dear hrsetyono,**
Untuk pemilihan ongkir pada saat pengisian data pengiriman, apakah tidak bisa dibuat pilihan ongkir berupa dropdown list?

Ada juga masalah lainnya berupa pilihan ongkir kadang suka tidak lengkap untuk beberapa kota yang saya cek (contoh: pengiriman ke Cibitung, Banten, tidak ada pilihan JNE YES, seringkali pilihan ongkir untuk Pos Indonesia tidak lengkap juga).

Masalah lainnya lagi ketika mencoba mengaktifkan mode pengiriman berbeda dari billing address (Mengisi shipping address), provinsi bisa dipilih namun kota tidak akan muncul kecuali jika provinsi nya DKI jakarta. Akibatnya perhitungan ongkir pun gagal.

**Regards,
VisiTekAsia**

**Comment by hrsetyono** [comment]
Halo VisiTek Asia

> Untuk pemilihan ongkir pada saat pengisian data pengiriman, apakah tidak bisa dibuat pilihan ongkir berupa dropdown list?

Pemilihan ongkir berupa checklist itu dari built-in Woocommerce nya. Sepertinya bisa diubah melalui hook atau filter. Tetapi lebih baik kalau dalam bentuk plugin terpisah.

> Ada juga masalah lainnya berupa pilihan ongkir kadang suka tidak lengkap untuk beberapa kota yang saya cek (contoh: pengiriman ke Cibitung, Banten, tidak ada pilihan JNE YES, seringkali pilihan ongkir untuk Pos Indonesia tidak lengkap juga).

API nya bukan saya yang membuat. Biasa tidak ada YES kalau memang jauh. Apakah kalau bapak/ibu cek di website JNE dengan destinasi sama ada pilihan YES nya?

> Masalah lainnya lagi ketika mencoba mengaktifkan mode pengiriman berbeda dari billing address (Mengisi shipping address), provinsi bisa dipilih namun kota tidak akan muncul kecuali jika provinsi nya DKI jakarta. Akibatnya perhitungan ongkir pun gagal.

Hmm saya memang belum sempat tes kalau Shipping address berbeda. Coba kalau ada waktu saya cek

**Comment by visitekasia** [comment]
**Dear hrsetyono,**
Makasih banget buat plugin nya, ditunggu nih fix nya untuk shipping address yang berbeda :)

**Regards,
VisiTekAsia**

**Comment by hrsetyono** [comment]
Maaf baru sempat kasih kabar sekarang. Saya tes Shipping address tidak ada masalah kok. Semua dropdown dari Country, Province, sampai City masih bekerja semua.

Ongkir pun terhitung sesuai alamat di shipping address.

Apakah mungkin clash dengan plugin lain?

**Comment by hrsetyono** [comment]
Sudah di fix di https://github.com/hrsetyono/woocommerce-indo-shipping/releases/tag/1.1.3b
