### ISSUE TITLE
kota dan kecamatan jadi satu

### ISSUE THREAD

**Issue by Yoviie** [hrsetyono/woocommerce-indo-shipping#24]
Saya punya trouble soal input kecamatan dan kota. Di panduan, kota dan kecamatan akan muncul secara otomatis, nah di website saya kota dan kecamatan jadi satu, tema yg saya pakai storefront, mohon bantuannya pak. 
SS di website saya : http://prntscr.com/gkwx6v
Terima kasih.

**Comment by hrsetyono** [comment]
Halo Yovie,

Sekarang kota dan kecamatan jadi satu karena banyak masalah alignment dengan theme2 lain.

Terima kasih
