### ISSUE TITLE
Setelah isi alamat, loading terus di bagian subtotal

### ISSUE THREAD

**Issue by berkedel** [hrsetyono/woocommerce-indo-shipping#26]
Ini versi yang saya pakai:
* Wordpress 4.8.2
* WooCommerce 3.1.2
* WooCommerce Indo Shipping 1.1.2

@hrsetyono Saya menemui kendala setelah customer mengisi alamat saat checkout. Setelah scroll ke bawah, terdapat loading yang terus menerus di bagian penghitungan shipping cost di subtotal. Adakah yang bisa membantu penyebab kasus seperti ini?

**Comment by hrsetyono** [comment]
@berkedel Apakan bapak sudah mengecek menggunakan theme Storefront? Kalau di storefront bisa, berarti ada yang salah dengan theme nya.

Mohon dikabari lagi hasilnya. trims

**Comment by berkedel** [comment]
@hrsetyono Terima kasih balasannya. Saya sudah mencoba versi lokal tidak ada masalah. Masalah di atas terjadi karena setingan docker saya yang bermasalah mungkin. Masih investigasi dimana letak permasalahannya.

**Comment by hrsetyono** [comment]
@berkedel Boleh share settingan docker nya? Buat set apa aja ya?

Sekarang aku cuma pakai buat otomatis upload theme yang sudah di commit ke git.
