### ISSUE TITLE
Opsi j&t tidak muncul

### ISSUE THREAD

**Issue by azfty** [hrsetyono/woocommerce-indo-shipping#27]
j&t express sudah ditambahkan di setting indo shipping, tetapi opsi shipping melalui j&t tidak muncul pada saat pembayaran.

Saya menggunakan API RajaOngkir Pro version.

**Comment by hrsetyono** [comment]
@azfty Setelah saya coba di Postman, ada kerusakan API dari Rajaongkir sendiri. Semua cost J&T tidak muncul. 

Bapak bisa tlg kirim email support ke rajaongkir utk menanyakan hal ini?

Trims

**Comment by azfty** [comment]
Saya coba test POST ke https://pro.rajaongkir.com/api/cost dengan query courier":"jnt" bisa dapat results":[{"code":"J&T","name":"J&T Express","costs":[{"service":"EZ","description":"Regular Service","cost":[{"value":32000,"etd":"","note":""}]

**Comment by hrsetyono** [comment]
Sepertinya ada yang salah dengan theme bapak, atau clash dengan plugin lain.

Saya coba di toko saya dan j&t bisa: https://imgur.com/a/4sAo3

Coba ganti theme dengan Storefront dan disable semua plugin yang berhubungan dengan WooCommerce

**Comment by azfty** [comment]
@hrsetyono 

Sudah saya coba. Tetap nggak bisa. Ini aneh sekali gan. Soalnya yang lain bisa semua kecuali j&t. Apakah cara query untuk mendapat ongkos j&t berbeda dengan yang lain?

**Comment by hrsetyono** [comment]
Bisa coba WP_DEBUG diaktifkan? Kalau ada error nanti muncul file debug log di wp-content

**Comment by azfty** [comment]
@hrsetyono

Sudah saya aktifkan tidak ada debug.log muncul.

**Comment by hrsetyono** [comment]
Bapak pakai versi berapa ya? Kalau sudah minimal 1.1.3 seharus nya tidak ada masalah

**Comment by azfty** [comment]
1.1.3b pak

**Comment by readonecc** [comment]
Sama, Opsi J&T tidak muncul di versi 1.1.4

**Comment by hrsetyono** [comment]
@readonecc Nah ini yang gw kurang tau penyebabnya. Di localhost dan hosting gw, lancar semua.

Ada yang bilang kemungkinan City Origin tertentu. Laporannya di kota Banyuwangi tidak bisa, gw tes di localhost tetap bisa.

Agan tes di kondisi gmn ya? Kalau bisa tolong di echo in `phpinfo()` nya

**Comment by readonecc** [comment]
Gan @hrsetyono Originnya Pamekasan, 
ane juga nyoba pake trial plugin ongkis kirim (tonjoostudio) ada pilihan untuk menggunakan API raja ongkir kan, lancar pake itu. bingung juga.

**Comment by readonecc** [comment]
http://herbathayyiba.com/pustaka-herba/plugins/woocommerce-indo-shipping-master/phpinfo.php
@hrsetyono

**Comment by bintaroweb** [comment]
Gan @hrsetyono ane nemu solusinya, yaitu caranya ubah $is_allowed = true; di file init-zones.php maka Ongkir J&T akan muncul.

Screenshoot : http://prntscr.com/kpwy3q
Hasilnya : http://prntscr.com/kpwyb3

Semoga bermanfaat untuk yang mengalami kendala tsb :-)

**Comment by hrsetyono** [comment]
@bintaroweb Kalau itu dibuat true, entar semua servis JNE jadi keluar walau yg dipilih cuma REG.

Tapi sekarang jadi tahu kalau permasalahan ada dibagian itu. Coba gw cek lagi. Trims

**Comment by hrsetyono** [comment]
Fixed #60
