### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /var/www/bakoelkoffie/wp-content/plugins/woocommerce-indo-shipping/admin/wcis-data.php on line 95

### ISSUE THREAD

**Issue by delpierrol** [hrsetyono/woocommerce-indo-shipping#28]
Saya kena error Parse error: syntax error, unexpected '[' in /var/www/bakoelkoffie/wp-content/plugins/woocommerce-indo-shipping/admin/wcis-data.php on line 95

ketika akan activate pluginnya

**Comment by hrsetyono** [comment]
PHP versi nya berapa mas? Sepertinya versi di bawah 5.6
