### ISSUE TITLE
Beberapa Kota Tidak Bisa Di Klik

### ISSUE THREAD

**Issue by johanlimm** [hrsetyono/woocommerce-indo-shipping#29]
Halo, sepertinya ada beberapa Kota seperti Malang dan Surabaya (saya belum cek semuanya) yang tidak bisa di pilih saat checkout. Saran saya lebih bagus dropdown kabupaten dan dropdown kecamatan dipisah saja.

**Comment by johanlimm** [comment]
<img width="1280" alt="screen shot 2017-10-24 at 5 16 46 pm" src="https://user-images.githubusercontent.com/1007213/31937585-2470c43e-b8df-11e7-8528-f827c551ba2f.png">

**Comment by hrsetyono** [comment]
Halo, yang bold itu sebenarnya label dari <optgroup>, untuk menghitung kecamatan memang harus memilih kecamatan.

Awalnya saya pisah jadi 2 tetapi jadi jauh lebih rumit, akhirnya digabung.

Solusi alternatif menambahkan nama kota di setiap kecamatan, jadi kalau di search, keluar semua. Misal `Jakarta - Kebon Jeruk`, atau `Jakarta - Kelapa Gading`.

Karena waktu, saya masih blm bisa mengupdate plugin ini, silahkan di fork plugin nya, nanti saya merge kalau berhasil..

**Comment by hrsetyono** [comment]
Sudah di fix di https://github.com/hrsetyono/woocommerce-indo-shipping/releases/tag/1.1.3

**Comment by johanlimm** [comment]
Thanks Pak! Really appreciate it. Best shipping plugin so far. Maaf merepotkan.
