### ISSUE TITLE
Kesalahan pada file provinces.json

### ISSUE THREAD

**Issue by johanlimm** [hrsetyono/woocommerce-indo-shipping#30]
Di line ke 8 ganti   "SS": 28,   menjadi   "SS": 33,

**Comment by hrsetyono** [comment]
Itu untuk membenarkan apa ya? Mohon diberi konteks lebih detail. Trims

**Comment by kusnandar** [comment]
"BA": 1,
  "BB": 2,
  "BT": 3,
  "BE": 4,
  "YO": 5,
  "JK": 6,
  "GO": 7,
  "JA": 8,
  "JB": 9,
  "JT": 10,
  "JI": 11,
  "KB": 12,
  "KS": 13,
  "KT": 14,
  "KI": 15,
  "KU": 16,
  "KR": 17,
  "LA": 18,
  "MA": 19,
  "MU": 20,
  "AC": 21,
  "NB": 22,
  "NT": 23,
  "PA": 24,
  "PB": 25,
  "RI": 26,
  "SR": 27,
  "SS": 28,
  "SN": 28,
  "ST": 29,
  "SG": 30,
  "SA": 31,
  "SB": 32,
  "SU": 34,

--
doble ID 28 dan tidak ada ID 33 ?

**Comment by hrsetyono** [comment]
Sudah di fix di 1.1.4 pak. Terima kasih laporan nya
