### ISSUE TITLE
No Shipping Methods

### ISSUE THREAD

**Issue by kusnandar** [hrsetyono/woocommerce-indo-shipping#31]
Problem yang sama...

> "There are no shipping methods available. Please double check your address, or contact us if you need any help."

![image](https://user-images.githubusercontent.com/31136012/32765586-bbe6be18-c93d-11e7-90f5-457949028919.png)

menggunakan http biasa
theme Storefront nya woocommerce

_
terima kasih atas bantuannya

**Comment by hrsetyono** [comment]
Tolong dicoba nonaktifkan semua plugin kecuali WooCommerce dan Indo Shipping nya.

Agak heran juga kenapa ada yg mengalami bug ini. Di tempat saya semua oke2 saja.

**Comment by kusnandar** [comment]
Setelah saya non aktifkan [WC Marketplace](https://wc-marketplace.com/) baru fitur ongkos kirimnya berjalan normal.

Ada cara supaya plugin tersebut bisa aktif juga,
Kebetulan websitenya memang untuk Marketplace (banyak vendor)

**Comment by hrsetyono** [comment]
@kusnandar wah maaf kalau untuk itu saya ga tau masalahnya mas. Coba dicek WC Marketplace nya ada kode yang gonta ganti shipping cost atau ga.
