### ISSUE TITLE
Kenapa J&T untuk kota tertentu tidak berfungsi ya?

### ISSUE THREAD

**Issue by ghost** [hrsetyono/woocommerce-indo-shipping#33]
Saya memakai asal kota Banyuwangi. JNE, POS, dan TIKI berfungsi dengan baik tapi untuk J&T tidak berfungsi http://prntscr.com/hbwy46 sudah memasukkan EZ reguler juga http://prntscr.com/hbwz4f Sebelumnya saya menghubungi Raja Ongkir lalu disarankan begini http://prntscr.com/hbx0fb

**Comment by hrsetyono** [comment]
Ini bug yang aneh, kalau di set ke kota tertentu seperti Semarang, J&T nya tiba2 bisa.

Saya tidak tahu penyebabnya, kalau ada ide tolong di share trims.

**Comment by asisten** [comment]
@filmarew   sesuai saran rajaongkir: https://image.ibb.co/i5Gojm/ss.jpg

**Comment by andusatria** [comment]
hal yg sama nih..
ada yg tau fix nya gk om?

**Comment by hrsetyono** [comment]
Fixed #60
