### ISSUE TITLE
Ongkirnya jadi jutaan

### ISSUE THREAD

**Issue by nsyakroni** [hrsetyono/woocommerce-indo-shipping#36]
Kira kira apa yang salah ya, lum lama ini saya nyobain pluginnya bpk Henner R Setyono. Namun di cart ongkir yang muncul jadi jutaan??
![screenshot_51](https://user-images.githubusercontent.com/15082774/34070855-8e6b31ce-e221-11e7-85aa-b998f706bb86.png)

**Comment by hrsetyono** [comment]
Saya baru tes di toko saya tidak masalah, apakah berat yang bapak masukkan satuan nya KGram tapi bapak kira Gram?

**Comment by nsyakroni** [comment]
Bener2.. Tadi di periksa ternyata salah settingan berat, ternyata masih settingan KG. Padahal Harusnya disetting ke Gram.
Maklum produknya hasil import massal.

Terimakasih banyak
