### ISSUE TITLE
Konfigurasi kurir tidak ada

### ISSUE THREAD

**Issue by alfarioekaputra** [hrsetyono/woocommerce-indo-shipping#38]
Sore, mau tanya ditempa saya tidak muncul konfigurasi untuk pilihan kurir

![image](https://user-images.githubusercontent.com/650641/34150443-f50e7466-e4da-11e7-9562-6c2a21c65e59.png)

kalau saya liat di wiki ada

![image](https://user-images.githubusercontent.com/650641/34150472-060cb296-e4db-11e7-9c63-84ef39cec519.png)

**Comment by hrsetyono** [comment]
Perlu beli API Key Pro dari Rajaongkir gan.

Disclaimer: saya tidak ada hubungan dengan Rajaongkir

**Comment by alfarioekaputra** [comment]
saya sudah menggunakan api key yang pro, ternyata harus di klik save changes dulu baru muncul konfigurasi kurirnya, 

terima kasih 👍
