### ISSUE TITLE
City origin tidak tampil

### ISSUE THREAD

**Issue by amiral** [hrsetyono/woocommerce-indo-shipping#4]
Mas boleh minta bantuan kok city origin sy tidak tampil ya? Padahal sudah di save berkali2.

**Comment by hrsetyono** [comment]
Apakah sudah pakai RajaOngkir PRO? Atau kemungkinan API nya lagi mati, bisa di cek di website nya rajaongkir. Kalau disana jalan, berarti bukan.

**Comment by amiral** [comment]
Sudah pakai yang pro. Bisa minta link untuk pengecekkan apikeynya mas? 
Soalnya say cari2 blm ketemu ya dibagian mananya.

**Comment by hrsetyono** [comment]
Bisa dicek disini http://rajaongkir.com/widget/buat

Jalan kok API nya

**Comment by amiral** [comment]
Iya mas. rajaongkir nya sih jalan. Tp pas dibagian di pengaturan city originnya gak tampil daftar kotanya.
Ini lagi sy coba gnti template. Semoga pengaruh template.

**Comment by hrsetyono** [comment]
Apakah specs server nya sesuai ini?

> REQUIREMENT: PHP 5.6 and WooCommerce 2.6+
