### ISSUE TITLE
Dropdown City tidak muncul saat checkout ketika mengisi billing address di my account

### ISSUE THREAD

**Issue by alfarioekaputra** [hrsetyono/woocommerce-indo-shipping#40]
mas @hrsetyono  mau tanya ketika saya mengisi city billing address di myaccount, saat ini kolom city di myaccount berupa textbox, pada saat checkout otomatis terisi kolom city tetapi kolomnya tidak berupa combobox melainkan textbox, mungkin mas ada pengalaman tentang masalah ini? 

terima kasih

**Comment by hrsetyono** [comment]
Wah belum pernah ngotak ngatik sampai ke My Account page. Akan saya tambahkan tapi tidak bisa dalam waktu dekat ini.

Kalau mas @alfarioekaputra bisa bantu, boleh di fork nanti saya merge.
