### ISSUE TITLE
There are no shipping methods available

### ISSUE THREAD

**Issue by gusmaow** [hrsetyono/woocommerce-indo-shipping#42]
Menu dropdown city tidak bisa dipilih, There are no shipping methods available
![image](https://user-images.githubusercontent.com/35989272/35609777-4c7af436-0691-11e8-957e-ebd37f797005.png)

**Comment by hrsetyono** [comment]
Bisa coba ganti theme storefront? Kalau masih tidak bisa coba disable semua plugin lain kecuali shipping ini dan woocommerce

**Comment by hrsetyono** [comment]
Penyebabnya kemungkinan besar PHP di hosting agan tidak support CURL dan ALLOW_URL_FOPEN. Bisa minta support mereka untuk diaktifkan
