### ISSUE TITLE
Mohon saat di activin selalu error

### ISSUE THREAD

**Issue by mayarana** [hrsetyono/woocommerce-indo-shipping#43]
Mohon bantuanya mas..saat di activin selalu error seperti gambar dibawah ini..mohon solusinya.
![error plugin](https://user-images.githubusercontent.com/35993831/35615993-6cf9ec3e-06a6-11e8-8353-c99c5ca2ea7c.jpg)
 saya pakai theme storefront terbaru dan woocommerce terbaru dengan setingan HTTPS

**Comment by hrsetyono** [comment]
Sepertinya PHP versi lama ya? Minimal versi 5.6 sesuai yang saya tulis di README nya

**Comment by mayarana** [comment]
oke..clear..ternyata betul php saya versi 5.5

makasih banyak atas solusinya
