### ISSUE TITLE
HTTPS problem

### ISSUE THREAD

**Issue by readonecc** [hrsetyono/woocommerce-indo-shipping#46]
Kira-kira kapan https nya bisa nih?
sayang banget.
Ada issue juga punya ane di situs satu lagi, jd seteleah aktivasi api raja ongkir ngga ada pilihan kurir2nya di bawah, hanya ada kolom pilihan kota asal pengiriman, itu pun ngga bisa dipilih, ngga bisa diapa2in, sudah coba deaktavsi semua plugin tapi sama, apa karena sebelumnya pake IThemes Security ya?

**Comment by readonecc** [comment]
jadi begini:
https://drive.google.com/open?id=15TI2qH504Ayr3GmOSPC94SGWfH7BXxnP

kira-kira kenapa ya?

**Comment by hrsetyono** [comment]
HTTPS ternyata bukan masalah gan. Toko2 klien ku juga tidak masalah setelah pindah HTTPS.

Coba di disable semua plugin yang kira2 bisa tabrakan seperti theme security itu.

Trims

**Comment by readonecc** [comment]
PHP nya sudah pake versi 7, curl juga sudah diaktifkan barusan, tapi tetep ngga pilihan kurir sama ngga bisa pilih kota asal saat settings, seperi gambar di atas

**Comment by readonecc** [comment]
sudah disable semua plugin, termasuk Ithemes, dan dicoba di website lain yg pake Ithemes juga bisa, heran ini kenapa bisa begini.

**Comment by readonecc** [comment]
bahkan sudah fresh install menggunakan subdomain di hosting yang sama, juga ngga bisa, masalahnya sama. kira2 sebabnya apa ya?

**Comment by readonecc** [comment]
Sudah tanya ke penyedia hosting, jawabannya cuma beginii, padahal udah dibilang setelah fresh install terjadi masalahnya.
https://drive.google.com/file/d/11WeHM5x0aySoX0ydWMrH3oCtyvjDAKsI/view?usp=sharing

**Comment by hrsetyono** [comment]
Coba di tes di localhost WAMP gan. Hosting yang dipake apa ya? Sepertinya agak terbatas

**Comment by readonecc** [comment]
Hostingnya di Qwords ini, bisnis hosting.
ada dua akun ane di Qwords, 3 domain di 1 akun ngga bisa semua,
1 domain di akun Qwords yang lain lancar.
1 domain di siteground lancar.

ini sama Qwords lg dicoba, mereka saya kasih demo subdomain yg ngga jalan pluginnya, habis itu mereka bilang sudah bisa di subdomain itu, entah diapain, akhirnya ane tanya masalahnya di mana dr kemaren, tp belum dijawab. ntar klo dijawab ane share di sini, biar klo ada permasalahan sama orang-orang bisa cepat mengatasinya

**Comment by hrsetyono** [comment]
Oke berarti kemungkinan ada masalah dari hosting nya. Tolong dikabari penyebab nya kalau sudah dapat info. Trims

**Comment by readonecc** [comment]
jawaban dari pihak hosting provider:
Kami informasikan untuk setting yang dilakukan butuh enable allow_url_fopen di hosting, setting bisa dilakukan melalui select php version pada cpanel. :)

Tapi di website ane satu lagi ngga bisa, dia berikan kode errornya:
[17-Mar-2018 03:22:06 UTC] PHP Warning:  file_get_contents(..............plugins/woocommerce-indo-shipping-master/data/couriers.json): failed to open stream: no suitable wrapper could be found in /home/r........./......../......./......../plugins/woocommerce-indo-shipping-master/admin/wcis-data.php on line 117
[17-Mar-2018 03:22:06 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/r........./......../......./......../plugins/woocommerce-indo-shipping-master/admin/wcis-data.php on line 48

**Comment by hrsetyono** [comment]
Ah oke gan, trims infonya, akan saya tambahkan di bagian requierment.

Selama ini hosting yang saya pakai udah default ada itu, jadi tidak tahu kalau butuh allow_url_fopen segala.

**Comment by readonecc** [comment]
Baik, terima kasih.
Klo bisa request fitur keterangan berat pengiriman di checkout page.
Juga seperti masalah yg sebelumnya pernah saya lihat di sini (https://github.com/hrsetyono/woocommerce-indo-shipping/issues/40) untuk fill address di my account dibuat seperti di checkout page.
Tentunya klo agannya sudah senggan dan sempat.
Terima kasih banyak gan, pluginnya sangat membantu.
