### ISSUE TITLE
beberapa Metode JNE dan POS tidak muncul di halaman checkout.

### ISSUE THREAD

**Issue by qolbu** [hrsetyono/woocommerce-indo-shipping#47]
Metode JNE saya setting semua metode masuk, OKE, REG & YES begitu juga POS. Tapi di halaman checkout yang muncul cuma JNE CTC & POS Paket Kilat.

kenapa yah mas ?
![screen shot 2018-04-24 at 8 44 24 am](https://user-images.githubusercontent.com/11640681/39161609-c29d8818-479b-11e8-9f39-cb13542c58b6.png)

**Comment by hrsetyono** [comment]
Karena memang servis lain seperti YES tidak sampai ke kota itu. Kalau kirim ke kota yang dekat2 memang biasa tidak ada YES.

Bisa coba di cek ke website JNE nya sendiri. Kalau ternyata ada, tolong laporkan lagi bug nya. Trims

**Comment by hrsetyono** [comment]
CTC itu sepertinya servis jarak dekat, jadi lebih murah dan cuma available kalau dekat
