### ISSUE TITLE
Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by qolbu** [hrsetyono/woocommerce-indo-shipping#48]
Mas saya coba mengaktifkan error ini Parse error: syntax error, unexpected '[' in /.../admin/wcis-data.php on line 95

**Comment by hrsetyono** [comment]
Sepertinya PHP versi yang tidak saya dukung. Di depan ada tulisan requirement nya

**Comment by qolbu** [comment]
oo baik, terima kasih.
