### ISSUE TITLE
API Pro Harus beli ?

### ISSUE THREAD

**Issue by tedyhk** [hrsetyono/woocommerce-indo-shipping#49]
Kita harus beli Api Pro?

**Comment by haifahrul** [comment]
Plugin ini di rekomendasikan menggunakan API versi Pro dari Raja Ongkir, artinya Anda perlu membeli nya / sewa di https://rajaongkir.com/ .

Setahu saya, plugin ini tidak support untuk versi free API.

**Comment by hrsetyono** [comment]
Yep harus Pro karena kalau pakai Free pun hasil nya tidak akurat karena tidak support sampai ke Kecamatan.

**Comment by tedyhk** [comment]
Yah, saya butuh yang free sebenernya. Hanya untuk tugas. Ok thanks 😊🙏
