### ISSUE TITLE
Menysuaikan ongkir sesuai weight

### ISSUE THREAD

**Issue by mangcoding** [hrsetyono/woocommerce-indo-shipping#5]
Mas bagaimana caranya supaya ongkir disesuaikan dengan total berat dari barang yang kita pilih

**Comment by hrsetyono** [comment]
Seharusnya berat sudah otomatis dihitung saat checkout.

**Comment by cubebali** [comment]
sepertinya nggak terhitug otomatis pak.. saya coba bandingkan di website saya dan dari web aslinya nggak sama..

**Comment by hrsetyono** [comment]
Kalkulasi weight sudah saya perbaiki di update 1.1.2  https://github.com/hrsetyono/woocommerce-indo-shipping/releases/tag/1.1.2

Ternyata saya lupa konversi dari kilogram jadi gram.

Trims
