### ISSUE TITLE
API key agar tidak nampak

### ISSUE THREAD

**Issue by readonecc** [hrsetyono/woocommerce-indo-shipping#50]
Bisa ngga gan API keynya dibuat jadi ******* begitu misalnya, biar klo dipake di toko orang mereka ngga bisa lihat API keynya.?
BTW JnT belum fix ya?

**Comment by hrsetyono** [comment]
> Bisa ngga gan API keynya dibuat jadi *******

Ide bagus gan. Di `/admin/init-main.php` line 35 cukup diganti type jadi "password". Sementara silahkan diganti sendiri dulu.

> BTW JnT belum fix ya?

Untuk JnT gw benar2 kurang tau penyebab nya. Mungkin agan bisa bantu cari2?

**Comment by willyarisky** [comment]
@hrsetyono sepertinya issue ini bisa di close juga.

**Comment by hrsetyono** [comment]
Iya sepertinya dulu pernah aku update
