### ISSUE TITLE
Ubah Posisi Provinsi saat Checkout

### ISSUE THREAD

**Issue by bintaroweb** [hrsetyono/woocommerce-indo-shipping#53]
Gan tau cara ubah Posisi Provinsi saat Checkout biar diatas sebelum Kota?

**Comment by hrsetyono** [comment]
Banyak di mbah google https://www.google.co.id/search?q=woocommerce+change+checkout+field+position&oq=woocommerce+change+checkout+field+position&aqs=chrome..69i57j69i64.5332j0j7&sourceid=chrome&ie=UTF-8
