### ISSUE TITLE
Dropdown Kota/Kabupaten tidak muncul setelah reload halaman checkout

### ISSUE THREAD

**Issue by readonecc** [hrsetyono/woocommerce-indo-shipping#54]
Ntah ini terjadi ke ane aja atau yang lain juga,
PHP 7.2 ane make, WooCommerce latest version

Jadi klo ane buka halaman checkout, masukkan provinsi, ntar dropdwon kotanya muncul, 
tapi klo ane reload halaman checkout, atau keluar dari halaman checkout, pas balik lagi dropdwon kotanya ngga muncil, yang keluar cuma nama kota diikuti angka (ane screenshot)
dropdown kota ngga muncul kecuali klo kita pilih provinsi yang lain dulu.
Ntah apa ada yang salah dengan konfigurasi ane, tapi ini masalah memang baru ane alami.

Oya, klo boleh request fitur biar plugin ini support WC Vendors, jadi setiap vendor bisa pilih basis pengiriman masing-masing. 

Thank you gan.

![Dropdown muncul, tapi setelah reload jadi ilang](https://user-images.githubusercontent.com/37444760/47889908-eb510080-de7e-11e8-9816-89b63cb92696.png)

![Dropdwon tidak muncul](https://user-images.githubusercontent.com/37444760/47889890-d7a59a00-de7e-11e8-94d2-bc5a80845303.png)

**Comment by willyarisky** [comment]
Saya sudah pull ke repo ini terkain bug ini tetapi belom di approve, sementara bisa di download di repo saya https://github.com/willyarisky/woocommerce-indo-shipping/archive/1.1.4.zip
