### ISSUE TITLE
tidak support di woocommerce 3.0.4

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#6]
pak mhon bantuannya untuk woocommerce 3.0.4 karena saya cb tidak muncul shipping di review product, klw di woocommerce 2.0 normal aja pak gak ada masalah ketika di upgrade ke 3.0.4 tidak jalan. statusnya seeprti ini terus There are no shipping methods available. Please double check your address, or contact us if you need any help.

**Comment by hrsetyono** [comment]
Plugin memang belum saya update untuk support 3.x. Apakah banyak improvement dari 2.x?

Untuk sementara, bapak bisa downgrade ke 2.x dulu

**Comment by frezendisney** [comment]
kira2 kpn ya pak bisa di update ke versi 3.x fitur untuk berjualan bagus di versi 3.x pak. dan themes saya merokemendasikan di versi 3.x pak. ?

**Comment by frezendisney** [comment]
problemnya sih saya di order review saat milih propinvsi dan kecamatan. harusnya kan reload ke order review di sidebar. nah ini tidak mau ngeload pak. klw di versi 2.7 dia bisa ngeload.

**Comment by hrsetyono** [comment]
@frezendisney Sudah saya update plugin nya pak, bisa didownload di tab Releases, jangan lupa ikuti petunjuk cara update nya.

Trims
