### ISSUE TITLE
J&T tidak mau mengeload Data harga

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#7]
terima kasih sebelumnya pak. saya sdh update versi nya pak. tapi saya mencoba fitur terbaru seperti RPX, J&T, and PCP. Dan saat saya tambahkan J&T seperti ini http://prntscr.com/f25pni . setelah saya save hasil dari itu yg tidak keluar hanya J&T harga ongkirnya tidak muncul padahal status sudh saya pilih sebagai opsi shipping. http://prntscr.com/f25pvv . kira2 knp ya pak ?

**Comment by frezendisney** [comment]
ini website yg sudah saya install pak https://carimug.com

**Comment by frezendisney** [comment]
oh iya pak saya cb klick place order tidak bisa pak. padahal saya sdh klik tarif pengirimannya. selalu muncul No shipping method has been selected. Please double check your address, or contact us if you need any help. bs di cek di carimug.com

**Comment by frezendisney** [comment]
saya nemu bugs lagi pak. posisi phone & email harusnya di atas akan tetapi jadi paling bawah http://prntscr.com/f271mt . dan harusnya kan saat sdh mendaftar data shipping sdh otomatis tersimpat. harusnya dia otomatis mengambil data harga. ini tidak mau pak. jdi harus click ulang lagi baru bisa muncul list harganya. di versi lama klw sdh pernah daftar tinggal pilih shipping aja saat order. ini harus di click ulang lagi baru bisa muncul. terima kasih pak

**Comment by frezendisney** [comment]
seperti ini pak dia tidak otomatis muncul http://prntscr.com/f272ti

**Comment by hrsetyono** [comment]
@frezendisney Untuk peletakan field nya memang aneh. Sejak 3.0 default seperti itu, dan tidak bisa diganti. Saya coba fresh installation pakai theme Storefront juga seperti itu.

Untuk harga yang tidak muncul dah harus klik ulang, itu perubahan di 3.0, coba saya cari cara di akali.

J&T di tempat saya jalan. apa API bapak Pro?

**Comment by frezendisney** [comment]
iya pak @hrsetyono saya pakai pro version. untuk place order yg gk bisa di klik selalu notif shipping tidak ditemukan. kira2 ada solusi pak? jdi mau checkout tidak bisa dikarena tidak ada shipping yg digunakan,.

**Comment by hrsetyono** [comment]
@frezendisney sudah saya update di Releases pak
