### ISSUE TITLE
field city muncul kode tambahan

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#8]
ini fieldnya fungsinya gmn y pak ? http://prntscr.com/f2eqco karena ada mode ketik ada mode select. dan funsingnya sepertinya sm. dan di akhir bagian pilihan kode ada kode tambahan. apabila itu di hilangan apakah bisa pak ? semacam ganti style menjadi display:none;

oh iya pak. untuk J&T di tempat bpk bisa ? punya demo sampleny pak ? agar saya tahu. karena disana tidak bisa di gunakan.

**Comment by hrsetyono** [comment]
Oh itu saya lupa hide field nya. Sudah ada release baru beta3 untuk fix nya.

Untuk J&T saya coba di localhost jalan. belum ada toko saya yg pakai J&T. Coba bapak test API key nya di Postman, apakah ada return j&t

**Comment by frezendisney** [comment]
oh gitu. sudh saya update ke beta_3 . untuk posisi field kira2 bisa dirubah gk ya pak ke atas http://prntscr.com/f2exu8 . dan akan pengaruh tidak ke plugin shipping

**Comment by hrsetyono** [comment]
@frezendisney masih belum nemu cara mengubahnya, sepertinya ada perubahan filter. Kalau bisa bapak bantu otak atik ya, trims

**Comment by frezendisney** [comment]
srkg sih sdh bisa pak. saya pakai plugin ini woo-easy-checkout-field . tapi untuk manualnya saya dpt disini https://businessbloomer.com/woocommerce-move-reorder-fields-checkout-page/ untuk versi 3.0

**Comment by frezendisney** [comment]
pak ada bugs disini http://prntscr.com/f2fg0n . klw dibuat tetap tampil jgn di hidden bisa pak untuk disctriknya? karena apabila di hidden. display bagian  create account paling bawah naik ke bagian colom city

**Comment by hrsetyono** [comment]
Oke, sudah saya show district field nya di beta4. Urutan field juga sudah saya tambahkan.

Sebenarnya setelah dipikir, masalah urutan field tidak seharus nya di plugin ini karena setiap toko kebutuhannya beda2, sementara oke lah.
