### ISSUE TITLE
reorder field

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/woocommerce-indo-shipping#9]
pak maaf klw yg beta 4 untuk reorder fieldnya jdi berantakan. jadi saat saya lihat log perubahan di githut bpk diperubbahan field saya commend http://prntscr.com/f2fo4g . soalnya defaultnya jadi berantakan. cb aja bpk check. urutannya betuk stylenya jdi berubah.

**Comment by frezendisney** [comment]
apa ini karena saya pakai plugin tambahan ya. buat mengatur perubahan fielnya. klw ini karena plugin tambahaan. abaikan saja. jadi defaultnya posisinya jdi berubah. memang sih harus plugin ini gk ada hubungan dengan field karena ada plugin lain yg mendukung perubahan field checkout.

**Comment by hrsetyono** [comment]
Iya itu karena plugin nya dobel2. Lebih baik yang kode saya utk ganti field di disable aja

**Comment by frezendisney** [comment]
ok siap. terima kasih. bila saya temukan bugs saya kbrin lagi. thanks pak
